name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Este paso busca tu archivo se llame como se llame y lo prepara
      - name: Prepara el archivo principal
        run: |
          find . -name "*.py" -exec mv {} main.py \;
          echo "Archivo preparado correctamente"

      - name: Build with Buildozer
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MiJuegoSnake
          path: bin/*.apk
